module:
  mounts:
    - source: blocks
      target: layouts/partials/blocks/
      includeFiles: '**.html'
    - source: sections
      target: layouts/section/
      includeFiles: '**.html'
    - source: views
      target: layouts/partials/views/
      includeFiles: '**.html'
    
